# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: |
        mkdir -p dist
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/SimpleHttpFileServer-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Archive Binaries
      uses: actions/upload-artifact@v4
      with:
        name: simple-http-file-server-binaries
        path: dist/

  release:
    needs: build   # 等待 build 完成
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: simple-http-file-server-binaries
          path: dist/

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          name: Latest Release          # Release 名称
          tag_name: latest              # 固定的 tag 名称
          files: dist/*                 # 上传的文件
          prerelease: false
          body: |
            Automated build from the main branch.
            Includes latest updates and improvements.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
